### ISSUE TITLE
Send Email Log raises an exception

### ISSUE THREAD

**Issue by luis901101** [RohitSurwase/UCE-Handler#7]
In versions previous to Android 8, this works fine, I've just seen the problem in Android >= 8, API 26
**_Nothing better than the self UCEHandler log..._**

`***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: samsung
Device: greatlte
Model: SM-N950F
Manufacturer: samsung
Product: greatltexx
SDK: 26
Release: 8.0.0

***** APP INFO 
Version: 1.0.0 Alpha 1.0
Installed On: 2018-12-17 06:00:53
Updated On: 2019-01-09 18:00:16
Current Date: 2019-01-23 12:39:50

***** ERROR LOG 
android.os.FileUriExposedException: file:///storage/emulated/0/AppErrorLogs_UCEH/MYAPP_Error-Log_2019-01-23_12%3A39%3A44.txt exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
	at android.net.Uri.checkFileUriExposed(Uri.java:2356)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:944)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10480)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10486)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10465)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
	at android.app.Activity.startActivityForResult(Activity.java:4564)
	at android.app.Activity.startActivityForResult(Activity.java:4522)
	at android.app.Activity.startActivity(Activity.java:4883)
	at android.app.Activity.startActivity(Activity.java:4851)
	at com.rohitss.uceh.UCEDefaultActivity.emailErrorLog(UCEDefaultActivity.java:161)
	at com.rohitss.uceh.UCEDefaultActivity.access$300(UCEDefaultActivity.java:55)
	at com.rohitss.uceh.UCEDefaultActivity$5.onClick(UCEDefaultActivity.java:92)
	at android.view.View.performClick(View.java:6896)
	at android.widget.TextView.performClick(TextView.java:12689)
	at android.view.View$PerformClick.run(View.java:26088)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

***** USER ACTIVITIES 
User Activities: 2019-01-23 12:39:24: UCEDefaultActivity created
2019-01-23 12:39:24: UCEDefaultActivity resumed

***** END OF LOG *****`

**Comment by jones139** [comment]
Yes - I just hit the same problem.   I fixed it by sending the COMMA_SEPARATED_EMAIL_ADDRESSES string with the intent rather than trying to access it in the UCEHandler class, as this was giving null for some reason.   My slightly customised version of your code with the fix in it is here if you want to see what I did to it: https://github.com/OpenSeizureDetector/Android_Pebble_SD/tree/V2.6/app/src/main/java/com/rohitss/uceh

**Comment by jones139** [comment]
One other thing, even once you have fixed the COMMA_SEPARATED_EMAIL_ADDRESSES issue, you get another exception to do with file URI permissions on Android 8.
I just commented out that bit of code because I at least get the stack trace without it.
https://github.com/OpenSeizureDetector/Android_Pebble_SD/blob/b217259ca5b07a60a3fef866e0f07d4bcbf60cee/app/src/main/java/com/rohitss/uceh/UCEDefaultActivity.java#L171
It looks like the official solution is to make some sort of ContentProvider to give the other activity access to this activity's files, but I haven't implemented that.

**Comment by RohitSurwase** [comment]
Thank you @jones139 for adding your working solution. As I am a bit busy with something else I could not check this issue. Once I do that I would also check if your suggestion is good or there are better solutions.
If you think your solution would work for all others, you can always contribute by creating a pull request.

**Comment by RohitSurwase** [comment]
Fixed with a new release. Please update your library to the latest.

**Comment by luis901101** [comment]
@RohitSurwase thanks
